#!/bin/bash

if [ $# -lt 2 ]; then
    echo "Usage: $0 rev-list reviewer summary [options]...";
    echo
    exit 1
fi

REVLIST=$1
REVIEWER=$2
SUMMARY=$3

if [[ $REVLIST == *.* ]]; then
  DESCRIPTION=$(git whatchanged $REVLIST)
  DIFF_CMD="git diff $REVLIST"
  if [ -z "$SUMMARY" ]; then
    echo Must provide a summary for a list of revisions
    exit 1
  fi
else
  DESCRIPTION=$(git whatchanged -n1 $REVLIST)
  DIFF_CMD="git show $REVLIST"
  if [ -z "$SUMMARY" ]; then
    SUMMARY=$(git log -n1 --pretty=format:%s $REVLIST)
  fi
fi

remote_url=$(
  git remote -v | egrep -o 'CDH/[a-zA-Z]+.git' | head -1)
if [ -z "$remote_url" ]; then
  echo 'could not figure out remote URL from remotes!'
  exit 1
fi

post-review --description="$DESCRIPTION" \
  --target-groups=platform \
  --target-people="$REVIEWER" \
  --diff-filename=<($DIFF_CMD) \
  --repository-url=git://github.sf.cloudera.com/$remote_url \
  --summary="$SUMMARY"
