#!/bin/bash

if [ $# -lt 2 ]; then
    echo "Usage: $0 rev-list [options]...";
    echo
    exit 1
fi

REVLIST=$1
REVIEWER=$2
SUMMARY=$3

if [[ $REVLIST == *.* ]]; then
  DESCRIPTION=$(git whatchanged $REVLIST)
  DIFF_CMD="git diff $REVLIST"
  if [ -z "$SUMMARY" ]; then
    echo Must provide a summary for a list of revisions
    exit 1
  fi
else
  DESCRIPTION=$(git whatchanged -n1 $REVLIST)
  DIFF_CMD="git show $REVLIST"
  if [ -z "$SUMMARY" ]; then
    SUMMARY=$(git log -n1 --pretty=format:%s $REVLIST)
  fi
fi


post-review --description="$DESCRIPTION" \
  --target-groups=platform \
  --target-people="$REVIEWER" \
  --diff-filename=<($DIFF_CMD) \
  --repository-url=git://github.sf.cloudera.com/CDH/hadoop.git \
  --summary="$SUMMARY"
