#!/bin/sh

confirm() {
  read ret
  if [ "$ret" != "n" ] && [ "ret" != "no" ]; then
    return 0
  else
    return 1
  fi
}

run_resolve() {
  rejfile=$1
  file=${rejfile%.rej}
  spawned=""
  if [ -n "$DISPLAY" ]; then
    xterm -e "git log -p $file" &
    spawned="$!"
  fi

  vim -o $rejfile $file
  echo 'Resolved? [Y/n]'
  if confirm ; then
    rm $rejfile
  fi

  if [ -n "$spawned" ]; then
    kill $spawned
  fi
}


for rejfile in $(find . -name \*.rej) ; do
  echo "Resolve $rejfile ?"
  read ret
  if [ "$ret" != "n" ] && [ "$ret" != "no" ] ; then
    run_resolve $rejfile
  fi
done
